export const classes = [
    '120  - Introduction to Programming',
    '121  - Object-Oriented Programming',
    '131  - Data Structures',
    '223J - Java Programming',
    '223N - Visual C# Programming',
    '223P - Python Programming',
    '223W - Swift Programming',
    '240  - Computer Organization and Assembly Language',
    '254  - Software Development with Open Source Systems',
    '301  - Programming Lab Practicum',
    '311  - Technical Writing for Computer Science',
    '313  - The Computer Impact',
    '315  - Professional Ethics in Computing',
    '323  - Compilers and Languages',
    '332  - File Structures and Database Systems',
    '335  - Algorithm Engineering',
    '349  - Web Front-End Engineering',
    '351  - Operating Systems Concepts',
    '353  - Introduction to Computer Security',
    '362  - Foundations of Software Engineering',
    '375  - Introduction to Data Science and Big Data',
    '386  - Introduction to Game Design and Production',
    '411  - Mobile Device Application Programming',
    '440  - Computer System Architecture',
    '449  - Web Back-End Engineering',
    '454  - Cloud Computing and Security',
    '456  - Network Security Fundamentals',
    '458  - Malware Analysis',
    '459  - Blockchain Technologies',
    '462  - Software Design',
    '463  - Software Testing',
    '464  - Software Architecture',
    '471  - Computer Communications',
    '474  - Parallel and Distributed Computing',
    '481  - Artificial Intelligence',
    '483  - Introduction to Machine Learning',
    '485  - Computational Bioinformatics',
    '490  - Undergraduate Seminar in Computer Science',
    '499  - Independent Study',
    '531  - Advanced Database Management',
    '535  - Advanced Algorithms',
    '541  - Systems and Software Standards and Requirements',
    '542  - Software Verification and Validation',
    '544  - Advanced Software Process',
    '546  - Modern Software Management',
    '547  - Software Measurement',
    '548  - Professional, Ethical and Legal Issues for Software Engineers',
    '552  - Cyber Forensics',
    '583  - Expert Systems Design Theory',
    '589  - Seminar in Computer Science',
    '597  - Project',
    '598  - Thesis',
    '599 - Independent Graduate Research'
];