import { CourseDetails } from './../_models/course-details';


export const CLASSDETAILS:CourseDetails[] = [
    { id: '120  ', 
       name: 'Introduction to Programming',
       description: 'Introduction to the concepts underlying all computer programming: design and execution of programs; sequential nature of programs; use of assignment, control and input/output statements to accomplish desired tasks; design and use of functions. Structured and object-oriented methodologies.',
       units: 3},
    { id: '121  ',
       name: 'Object-Oriented Programming',
       description: 'The object-oriented programming paradigm: classes, member functions, interfaces, inheritance, polymorphism, and exceptions. Design practices including encapsulation, decoupling, and documentation. Pointers/references and memory management. Recursion.',
       units: 3},
    { id: '131  ',
       name: 'Data Structures',
       description: 'Classical data structures: vector, linked list, stack, queue, binary search tree, and graph representations. Worst-case analysis, amortized analysis, and big-O notation. Object-oriented and recursive implementation of data structures. Self-resizing vectors and self-balancing trees. Empirical performance measurement.',
       units: 3},
    { id: '223C ',
       name: 'C Programming',
       description: 'Systems programming in the C language, including its syntax and semantics; essential idioms; important parts of the C11 and POSIX C APIs; security issues; and notable extensions libraries.',
       units: 3},
    { id: '223J ',
       name: 'Java Programming',
       description: 'Characteristics of Java: portable, robust, secure, object-oriented, high performance; using the Java environment; server administration; types, expressions and control flow; classes, interfaces and packages; threads; exceptions; class libraries; Java for the Internet; tools, the Java Virtual machine.',
       units: 3},
    { id: '223N ',
       name: 'Visual C# Programming',
       description: 'Characteristics of C#, object-oriented design concepts, control structures, methods, arrays, classes, objects, inheritance, polymorphism, exception handling, graphical user interfaces, multithreading, characters, strings, files, streams. Rudiments of the Unified Modeling Language Software development assignments.',
       units: 3},
    { id: '223P ',
       name: 'Python Programming',
       description: 'Characteristics of Python: portable, robust, secure, object-oriented, functional, high performance, extensible; types, expressions, and control flow; classes, abstract base classes, modules, and packages; threads; exceptions; Python standard library.',
       units: 3},
    { id: '223W ',
       name: 'Swift Programming',
       description: '',
       units: 3},
    { id: '240  ',
       name: 'Computer Organization and Assembly Language',
       description: 'Digital logic and architecture of a computer system, machine level representation of data, memory system organization, structure of low-level computer languages. Machine, assembly, and macro language programming. Principles of assembler operation, input-output programming, interrupt/exception handling. Laboratory programming assignments.',
       units: 3},
    { id: '254  ',
       name: 'Software Development with Open Source Systems',
       description: 'Philosophy of open source software development, open source operating systems such as Linux; open source development tools; open source programming languages, such as Python; open source software development processes; open source software licensing issues.',
       units: 3},
    { id: '301  ',
       name: 'Programming Lab Practicum',
       description: 'Intensive programming covering concepts learned in lower-division courses. Procedural and object oriented design, documentation, arrays, classes, file input/output, recursion, pointers, dynamic variables, data and file structures.',
       units: 3},
    { id: '311  ',
       name: 'Technical Writing for Computer Science',
       description: 'Develop documentation skills as used in the computer field. Proposals, feasibility studies, user guides and manuals, business communication and technical presentation. Case studies in professional ethics. Written and oral reports required.',
       units: 3},
    { id: '313  ',
       name: 'The Computer Impact',
       description: 'The effects of computers on society. Unanticipated consequences of computing technology for individuals, organizations, and institutions. Personal responsibility and legal ramifications. May not be applied toward Computer Science major requirements.',
       units: 3},
    { id: '315  ',
       name: 'Professional Ethics in Computing',
       description: 'Ethics and moral philosophy as applied to software and digital artifacts. Notions of rights, responsibilities, property, ownership, privacy, security, and professional ethics. Security obligations. Intellectual propertystatutes, licenses, and their terms. Oral and written reports are required.',
       units: 3},
    { id: '323  ',
       name: 'Compilers and Languages',
       description: 'Basic concepts of programming languages and principles of translation. Topics include history of programming languages, various programming paradigms, language design issues and criteria, design of compilers for modern programming languages.',
       units: 3},
    { id: '332  ',
       name: 'File Structures and Database Systems',
       description: 'Fundamental theories and design of database systems, the Structured Query Language (SQL), basic concepts and techniques of data organization in secondary storage. Topics include introduction to database systems, ER model, relational model, index structures and hashing techniques.',
       units: 3},
    { id: '335  ',
       name: 'Algorithm Engineering',
       description: 'Algorithm design using classical patterns: exhaustive search, divide and conquer, randomization, hashing, reduction, dynamic programming, and the greedy method. Asymptotic and experimental efficiency analysis. NP-completeness and decidability. Implementing algorithms to solve practical problems.',
       units: 3},
    { id: '349  ',
       name: 'Web Front-End Engineering',
       description: 'Concepts and architecture of interactive web applications, including markup, stylesheets and behavior. Functional and object-oriented aspects of JavaScript. Model-view design patterns, templates and frameworks. Client-side technologies for asynchronous events, real-time interaction and access to back-end web services.',
       units: 3},
    { id: '351  ',
       name: 'Operating Systems Concepts',
       description: 'Resource management, memory organization, input/output, control process synchronization and other concepts as related to the objectives of multi-user operating systems.',
       units: 3},
    { id: '353  ',
       name: 'Introduction to Computer Security',
       description: 'Security goals, security systems, access controls, networks and security, integrity, cryptography fundamentals, authentication. Attacks: software, network, website; management considerations, security standards in government and industry; security issues in requirements, architecture, design, implementation, testing, operation, maintenance, acquisition, and services.',
       units: 3},
    { id: '362  ',
       name: 'Foundations of Software Engineering',
       description: 'Basic concepts, principles, methods, techniques and practices of software engineering. All aspects of the software engineering fields. Use Computer-Aided Software Engineering (CASE) tools.',
       units: 3},
    { id: '375  ',
       name: 'Introduction to Data Science and Big Data',
       description: 'Techniques for data preparation, exploratory analysis, statistical modeling, machine learning and visualization. Methods for analyzing different types of data, such as natural language and time-series, from emerging applications, including Internet-of-Things. Big data platforms. Projects with real-world data.',
       units: 3},
    { id: '386  ',
       name: 'Introduction to Game Design and Production',
       description: 'Current and future technologies and market trends in game design and production. Game technologies, basic building tools for games and the process of game design, development and production.',
       units: 3},
    { id: '411  ',
       name: 'Mobile Device Application Programming',
       description: 'Introduction to developing applications for mobile devices, including but not limited to runtime environments, development tools and debugging tools used in creating applications for mobile devices. Use emulators in lab. Students must provide their own mobile devices.',
       units: 3},
    { id: '431  ',
       name: 'Database and Applications',
       description: 'Database design and application development techniques for a real world system. System analysis, requirement specifications, conceptual modeling, logic design, physical design and web interface development. Develop projects using contemporary database management system and web-based application development platform.',
       units: 3},
    { id: '439  ',
       name: 'Theory of Computation',
       description: 'Introduction to the theory of computation. Automata theory; finite state machines, context free grammars, and Turing machines; hierarchy of formal language classes. Computability theory and undecidable problems. Time complexity; P and NP-complete problems. Applications to software design and security.',
       units: 3},
    { id: '440  ',
       name: 'Computer System Architecture',
       description: 'Computer performance, price/performance, instruction set design and examples. Processor design, pipelining, memory hierarchy design and input/output subsystems.',
       units: 3},
    { id: '449  ',
       name: 'Web Back-End Engineering',
       description: 'Design and architecture of large-scale web applications. Techniques for scalability, session management and load balancing. Dependency injection, application tiers, message queues, web services and REST architecture. Caching and eventual consistency. Data models, partitioning and replication in relational and non-relational databases.',
       units: 3},
    { id: '452  ',
       name: 'Cryptography',
       description: 'Introduction to cryptography and steganography. Encryption, cryptographic hashing, certificates, and signatures. Classical, symmetric-key, and public-key ciphers. Block modes of operation. Cryptanalysis including exhaustive search, man-in-the-middle, and birthday attacks. Programing projects involving implementation of cryptographic systems.',
       units: 3},
    { id: '454  ',
       name: 'Cloud Computing and Security',
       description: 'Cloud computing and cloud security, distributed computing, computer clusters, grid computing, virtual machines and virtualization, cloud computing platforms and deployment models, cloud programming and software environments, vulnerabilities and risks of cloud computing, cloud infrastructure protection, data privacy and protection.',
       units: 3},
    { id: '455  ',
       name: 'Web Security',
       description: 'Concepts of web application security. Web security mechanisms, including authentication, access control and protecting sensitive data. Common vulnerabilities, including code and SQL attacks, cross-site scripting and cross-site request forgery. Implement hands-on web application security mechanisms and security testing.',
       units: 3},
    { id: '456  ',
       name: 'Network Security Fundamentals',
       description: 'Learn about vulnerabilities of network protocols, attacks targeting confidentiality, integrity and availability of data transmitted across networks, and methods for diagnosing and closing security gaps through hands-on exercises.',
       units: 3},
    { id: '458  ',
       name: 'Malware Analysis',
       description: 'Introduction to principles and practices of malware analysis. Topics include static and dynamic code analysis, data decoding, analysis tools, debugging, shellcode analysis, reverse engineering of stealthy malware and written presentation of analysis results.',
       units: 3},
    { id: '459  ',
       name: 'Blockchain Technologies',
       description: 'Digital assets as a medium of exchange to secure financial transactions; decentralized and distributed ledgers that record verifiable transactions; smart contracts and Ethereum; Bitcoin mechanics and mining; the cryptocurrency ecosystem; blockchain mechanics and applications.',
       units: 3},
    { id: '462  ',
       name: 'Software Design',
       description: 'Concepts of software modeling, software process and some tools. Object-oriented analysis and design and Unified process. Some computer-aided software engineering (CASE) tools will be recommended to use for doing homework assignments.',
       units: 3},
    { id: '463  ',
       name: 'Software Testing',
       description: 'Software testing techniques, reporting problems effectively and planning testing projects. Students apply what they learned throughout the course to a sample application that is either commercially available or under development.',
       units: 3},
    { id: '464  ',
       name: 'Software Architecture',
       description: 'Basic principles and practices of software design and architecture. High-level design, software architecture, documenting software architecture, software and architecture evaluation, software product lines and some considerations beyond software architecture.',
       units: 3},
    { id: '466  ',
       name: 'Software Process',
       description: 'Practical guidance for improving the software development process. How to establish, maintain and improve software processes. Exposure to agile processes, ISO 12207 and CMMI.',
       units: 3},
    { id: '471  ',
       name: 'Computer Communications',
       description: 'Introduction to digital data communications. Terminology, networks and their components, common-carrier services, telecommunication facilities, terminals, error control, multiplexing and concentration techniques.',
       units: 3},
    { id: '474  ',
       name: 'Parallel and Distributed Computing',
       description: 'Concepts of distributed computing; distributed memory and shared memory architectures; parallel programming techniques; inter-process communication and synchronization; programming for parallel architectures such as multi-core and GPU platforms; project involving distributed application development.',
       units: 3},
    { id: '481  ',
       name: 'Artificial Intelligence',
       description: '',
       units: 3},
    { id: '483  ',
       name: 'Introduction to Machine Learning',
       description: '',
       units: 3},
    { id: '485  ',
       name: 'Computational Bioinformatics',
       description: '',
       units: 3},
    { id: '490  ',
       name: 'Undergraduate Seminar in Computer Science',
       description: '',
       units: 3},
    { id: '499  ',
       name: 'Independent Study',
       description: '',
       units: 3},
    { id: '531  ',
       name: 'Advanced Database Management',
       description: '',
       units: 3},
    { id: '535  ',
       name: 'Advanced Algorithms',
       description: '',
       units: 3},
    { id: '541  ',
       name: 'Systems and Software Standards and Requirements',
       description: '',
       units: 3},
    { id: '542  ',
       name: 'Software Verification and Validation',
       description: '',
       units: 3},
    { id: '544  ',
       name: 'Advanced Software Process',
       description: '',
       units: 3},
    { id: '546  ',
       name: 'Modern Software Management',
       description: '',
       units: 3},
    { id: '547  ',
       name: 'Software Measurement',
       description: '',
       units: 3},
    { id: '548  ',
       name: 'Professional, Ethical and Legal Issues for Software Engineers',
       description: '',
       units: 3},
    { id: '552  ',
       name: 'Cyber Forensics',
       description: '',
       units: 3},
    { id: '583  ',
       name: 'Expert Systems Design Theory',
       description: '',
       units: 3},
    { id: '589  ',
       name: 'Seminar in Computer Science',
       description: '',
       units: 3},
    { id: '597  ',
       name: 'Project',
       description: '',
       units: 3},
    { id: '598  ',
       name: 'Thesis',
       description: '',
       units: 3},
    { id: '599  ',
       name: 'Independent Graduate Research',
       description: '',
       units: 3}
];