import { Course } from '../_models/course';

export const classes:Course[]= [
    {"id": '120  ',
     "name": 'Introduction to Programming'},
    {"id": '121  ',
     "name": 'Object-Oriented Programming'},
    {"id": '131  ',
     "name": 'Data Structures'},
    {"id": '223J ',
     "name": 'Java Programming'},
    {"id": '223N ',
     "name": 'Visual C# Programming'},
    {"id": '223P ',
     "name": 'Python Programming'},
    {"id": '223W ',
     "name": 'Swift Programming'},
    {"id": '240  ',
     "name": 'Computer Organization and Assembly Language'},
    {"id": '254  ',
     "name": 'Software Development with Open Source Systems'},
    {"id": '301  ',
     "name": 'Programming Lab Practicum'},
    {"id": '311  ',
     "name": 'Technical Writing for Computer Science'},
    {"id": '313  ',
     "name": 'The Computer Impact'},
    {"id": '315  ',
     "name": 'Professional Ethics in Computing'},
    {"id": '323  ',
     "name": 'Compilers and Languages'},
    {"id": '332  ',
     "name": 'File Structures and Database Systems'},
    {"id": '335  ',
     "name": 'Algorithm Engineering'},
    {"id": '349  ',
     "name": 'Web Front-End Engineering'},
    {"id": '351  ',
     "name": 'Operating Systems Concepts'},
    {"id": '353  ',
     "name": 'Introduction to Computer Security'},
    {"id": '362  ',
     "name": 'Foundations of Software Engineering'},
    {"id": '375  ',
     "name": 'Introduction to Data Science and Big Data'},
    {"id": '386  ',
     "name": 'Introduction to Game Design and Production'},
    {"id": '411  ',
     "name": 'Mobile Device Application Programming'},
    {"id": '440  ',
     "name": 'Computer System Architecture'},
    {"id": '449  ',
     "name": 'Web Back-End Engineering'},
    {"id": '454  ',
     "name": 'Cloud Computing and Security'},
    {"id": '456  ',
     "name": 'Network Security Fundamentals'},
    {"id": '458  ',
     "name": 'Malware Analysis'},
    {"id": '459  ',
     "name": 'Blockchain Technologies'},
    {"id": '462  ',
     "name": 'Software Design'},
    {"id": '463  ',
     "name": 'Software Testing'},
    {"id": '464  ',
     "name": 'Software Architecture'},
    {"id": '471  ',
     "name": 'Computer Communications'},
    {"id": '474  ',
     "name": 'Parallel and Distributed Computing'},
    {"id": '481  ',
     "name": 'Artificial Intelligence'},
    {"id": '483  ',
     "name": 'Introduction to Machine Learning'},
    {"id": '485  ',
     "name": 'Computational Bioinformatics'},
    {"id": '490  ',
     "name": 'Undergraduate Seminar in Computer Science'},
    {"id": '499  ',
     "name": 'Independent Study'},
    {"id": '531  ',
     "name": 'Advanced Database Management'},
    {"id": '535  ',
     "name": 'Advanced Algorithms'},
    {"id": '541  ',
     "name": 'Systems and Software Standards and Requirements'},
    {"id": '542  ',
     "name": 'Software Verification and Validation'},
    {"id": '544  ',
     "name": 'Advanced Software Process'},
    {"id": '546  ',
     "name": 'Modern Software Management'},
    {"id": '547  ',
     "name": 'Software Measurement'},
    {"id": '548  ',
     "name": 'Professional, Ethical and Legal Issues for Software Engineers'},
    {"id": '552  ',
     "name": 'Cyber Forensics'},
    {"id": '583  ',
     "name": 'Expert Systems Design Theory'},
    {"id": '589  ',
     "name": 'Seminar in Computer Science'},
    {"id": '597  ',
     "name": 'Project'},
    {"id": '598  ',
     "name": 'Thesis'},
    {"id": '599  ',
     "name": 'Independent Graduate Research'}
];