import { Teacher } from '../_models/teacher';

export const Teachers: Teacher[] = [
    { id: 'Alexander Gauf' },
    { id: 'Anand Panangadan' },
    { id: 'Anthony Le' },
    { id: 'Arash Sharif' },
    { id: 'Bach Ho' },
    { id: 'Beth Harnick-Shapiro' },
    { id: 'Bijan Hamidi' },
    { id: 'Bin Cong' },
    { id: 'Chang-Hyun Jo' },
    { id: 'Charles Siska' },
    { id: 'Christopher Ryu' },
    { id: 'Chun-I Chen' },
    { id: 'Daniel Rodgers' },
    { id: 'Dave Garcia-Gomez' },
    { id: 'David Heckathorn' },
    { id: 'Doina Bein' },
    { id: 'Eric May' },
    { id: 'Floyd Holliday' },
    { id: 'Hernan Manabat' },
    { id: 'James S. Choi' },
    { id: 'John Oates' },
    { id: 'Joseph Martinazzi' },
    { id: 'Kanika Sood' },
    { id: 'Kenneth Kung' },
    { id: 'Kenytt Avery' },
    { id: 'Kevin Wortman' },
    { id: 'Kyoung-Seop Shin' },
    { id: 'Lidia Morrison' },
    { id: 'Linh Trinh' },
    { id: 'Marc Velasco' },
    { id: 'Mark Hauchwitz' },
    { id: 'Mehdi Peiravi' },
    { id: 'Michael Shafae' },
    { id: 'Michael Turi' },
    { id: 'Mike Peralta' },
    { id: 'Mikhail Gofman' },
    { id: 'Mircea Dumbitrache' },
    { id: 'Natasha Anderson' },
    { id: 'Neeraj Gupta' },
    { id: 'Ning Chen' },
    { id: 'Paul Salvador Inventado' },
    { id: 'Pouya Radfar' },
    { id: 'Sara Ghadami' },
    { id: 'Sara Hariri' },
    { id: 'Shawn Graham' },
    { id: 'Shawn Wang' },
    { id: 'Shilpa Lakhanpal' },
    { id: 'Son Nguyen' },
    { id: 'Song Choi' },
    { id: 'Stephen May' },
    { id: 'Steven Cooper' },
    { id: 'Susan Barua' },
    { id: 'Swayam Pati' },
    { id: 'Sylvan Shulman' },
    { id: 'Teresa Shea' },
    { id: 'Thomas Bettens' },
    { id: 'Tiffany Babb' },
    { id: 'Tseng-Ching Shen' },
    { id: 'Wenlin Han' },
    { id: 'William McCarthy' },
    { id: 'Yoonsuk Choi' },
    { id: 'Yu Bai' },
    { id: 'Yun Tian' }
]