import { Teacher } from './teacher';

export const TEACHERS: Teacher[] = [
    { id: 1 , name: 'Alexander Gauf',           classes: 'CPSC 120', email: 'agauf@fullerton.edu'},
    { id: 2 , name: 'Anand Panangadan',         classes: 'CPSC 375 ', email: 'apanangadan@fullerton.edu'},
    { id: 3 , name: 'Anthony Le',               classes: 'CPSC 323', email: 'anthle@fullerton.edu'},
    { id: 4 , name: 'Arash Sharif',             classes: 'CPSC 547', email: 'arash.sharif@fullerton.edu'},
    { id: 5 , name: 'Bach Ho',                  classes: 'CPSC 311, CPSC 315', email: 'bho@fullerton.edu'},
    { id: 6 , name: 'Beth Harnick-Shapiro',     classes: 'CPSC 315', email: 'beth.harnick.shapiro@fullerton.edu'},
    { id: 7 , name: 'Bijan Hamidi',             classes: 'CPSC 121, CPSC 223C', email: 'bihamidi@fullerton.edu'},
    { id: 8 , name: 'Bin Cong',                 classes: 'CPSC 546, CPSC 597', email: 'bcong@fullerton.edu'},
    { id: 9 , name: 'Chang-Hyun Jo',            classes: 'CPSC 597 ', email: 'cjo@fullerton.edu'},
    { id: 10, name: 'Charles Siska',            classes: 'CPSC 335, CPSC 481', email: 'csiska@fullerton.edu'},
    { id: 11, name: 'Christopher Ryu',          classes: 'CPSC 491', email: 'tryu@fullerton.edu'},
    { id: 12, name: 'Chun-I Chen',              classes: 'CPSC 332, CPSC 531, CPSC 589', email: 'chuchen@fullerton.edu'},
    { id: 13, name: 'Daniel Rodgers',           classes: 'CPSC 463', email: 'danrodgers@fullerton.edu'},
    { id: 14, name: 'Dave Garcia-Gomez',        classes: 'CPSC 332', email: 'dgarcia-gomez@fullerton.edu'},
    { id: 15, name: 'David Heckathorn',         classes: 'CPSC 254, CPSC 353', email: 'dheckathorn@fullerton.edu'},
    { id: 16, name: 'Doina Bein',               classes: 'CPSC 479, CPSC 535', email: 'dbein@fullerton.edu'},
    { id: 17, name: 'Eric May',                 classes: 'CPSC 131, CPSC 311', email: 'ermay@fullerton.edu'},
    { id: 18, name: 'Floyd Holliday',           classes: 'CPSC 223J, CPSC 240', email: 'holliday@fullerton.edu'},
    { id: 19, name: 'Hernan Manabat',           classes: 'CPSC 456', email: 'hmanabat@fullerton.edu'},
    { id: 20, name: 'James S. Choi',            classes: '', email: ''},
    { id: 21, name: 'John Oates',               classes: 'CPSC 223P', email: 'joates@fullerton.edu'},
    { id: 22, name: 'Joseph Martinazzi',        classes: 'CPSC 313, CPSC 466', email: 'jmartinazzi@fullerton.edu'},
    { id: 23, name: 'Kanika Sood',              classes: 'CPSC 313', email: 'kasood@fullerton.edu'},
    { id: 24, name: 'Kenneth Kung',             classes: 'CPSC 353', email: 'kkung@fullerton.edu'},
    { id: 25, name: 'Kenytt Avery',             classes: 'CPSC 449, CPSC 483, CPSC 585', email: 'kavery@fullerton.edu'},
    { id: 26, name: 'Kevin Wortman',            classes: 'CPSC 335', email: 'kwortman@fullerton.edu'},
    { id: 27, name: 'Kyoung-Seop Shin',         classes: 'CPSC 332', email: 'kshin@fullerton.edu'},
    { id: 28, name: 'Lidia Morrison',           classes: 'CPSC 315', email: 'lmorrison@fullerton.edu'},
    { id: 29, name: 'Linh Trinh',               classes: 'CPSC 353, CPSC 471', email: 'ltrinh@fullerton.edu'},
    { id: 30, name: 'Marc Velasco',             classes: 'CPSC 362', email: 'mavelasco@fullerton.edu'},
    { id: 31, name: 'Mark Hauchwitz',           classes: 'CPSC 431', email: 'markhauchwitz@fullerton.edu'},
    { id: 32, name: 'Mehdi Peiravi',            classes: 'CPSC 121, CPSC 362', email: 'mepeiravi@fullerton.edu'},
    { id: 33, name: 'Michael Shafae',           classes: 'CPSC 120, CPSC 386', email: 'mshafae@fullerton.edu'},
    { id: 34, name: 'Michael Turi',             classes: 'CPSC 440', email: 'mturi@fullerton.edu'},
    { id: 35, name: 'Mike Peralta',             classes: 'CPSC 120', email: 'miperalta@fullerton.edu'},
    { id: 36, name: 'Mikhail Gofman',           classes: 'CPSC 599', email: 'mgofman@fullerton.edu'},
    { id: 37, name: 'Mircea Dumbitrache',       classes: 'CPSC 121', email: 'dgmircea@fullerton.edu'},
    { id: 38, name: 'Natasha Anderson',         classes: 'CPSC 351', email: 'nvanderson@fullerton.edu'},
    { id: 39, name: 'Neeraj Gupta',             classes: 'CPSC 545', email: 'neerajgupta@fullerton.edu'},
    { id: 40, name: 'Ning Chen',                classes: 'CPSC 545', email: 'nchen@fullerton.edu'},
    { id: 41, name: 'Paul Salvador Inventado',  classes: 'CPSC 121, CPSC 223W, CPSC 598', email: 'pinventado@fullerton.edu'},
    { id: 42, name: 'Pouya Radfar',             classes: 'CPSC 315', email: 'pradfar@fullerton.edu'},
    { id: 43, name: 'Sara Ghadami',             classes: 'CPSC 120, CPSC 131, CPSC 313, CPSC 362', email: 'sghadami@fullerton.edu'},
    { id: 44, name: 'Sara Hariri',              classes: 'CPSC 313', email: 'shariri@fullerton.edu'},
    { id: 45, name: 'Shawn Graham',             classes: 'CPSC 223P, CPSC 301', email: 'shagraham@fullerton.edu'},
    { id: 46, name: 'Shawn Wang',               classes: 'CPSC 332, CPSC 599', email: 'xwang@fullerton.edu'},
    { id: 47, name: 'Shilpa Lakhanpal',         classes: 'CPSC 131, CPSC 351', email: 'shlakhanpal@fullerton.edu'},
    { id: 48, name: 'Son Nguyen',               classes: 'CPSC 543 ', email: 'son_nguyen@fullerton.edu'},
    { id: 49, name: 'Song Choi',                classes: 'CPSC 541, CPSC 543 ', email: 'jchoi@fullerton.edu'},
    { id: 50, name: 'Stephen May',              classes: 'CPSC 121', email: 'stmay@fullerton.edu'},
    { id: 51, name: 'Steven Cooper',            classes: 'CPSC 311', email: 'stcooper@fullerton.edu'},
    { id: 52, name: 'Susan Barua',              classes: '', email: ''},
    { id: 53, name: 'Swayam Pati',              classes: 'CPSC 462', email: 'spati@fullerton.edu'},
    { id: 54, name: 'Sylvan Shulman',           classes: 'CPSC 362', email: 'eshulman@fullerton.edu'},
    { id: 55, name: 'Teresa Shea',              classes: 'CPSC 121', email: 'teshea@fullerton.edu'},
    { id: 56, name: 'Thomas Bettens',           classes: 'CPSC 131, CPSC 462', email: 'tbettens@fullerton.edu'},
    { id: 57, name: 'Tiffany Babb',             classes: 'CPSC 311', email: 'tibabb@fullerton.edu'},
    { id: 58, name: 'Tseng-Ching Shen',         classes: 'CPSC 411', email: 'jtcshen@fullerton.edu'},
    { id: 59, name: 'Wenlin Han',               classes: 'CPSC 459, CPSC 481', email: 'whan@fullerton.edu'},
    { id: 60, name: 'William McCarthy',         classes: 'CPSC 349, CPSC 351, CPSC 386, CPSC 484', email: 'wmccarthy@fullerton.edu'},
    { id: 61, name: 'Yoonsuk Choi',             classes: 'CPSC 440', email: 'yochoi@fullerton.edu'},
    { id: 62, name: 'Yu Bai',                   classes: 'CPSC 240', email: 'ybai@fullerton.edu'},
    { id: 63, name: 'Yun Tian',                 classes: 'CPSC 351, CPSC 471', email: 'ytian@fullerton.edu'},
];