import { Teacher } from './teacher';

export const TEACHERS: Teacher[] = [
    { id: 13, name: 'Anand Panangadan'},
    { id: 6, name: 'Bin Cong'},
    { id: 11, name: 'Chang-Hyun Jo'},
    { id: 1, name: 'Christopher Ryu'},
    { id: 3, name: 'Doina Bein'},
    { id: 9, name: 'Floyd Holliday'},
    { id: 5, name: 'James S. Choi'},
    { id: 15, name: 'Kanika Sood'},
    { id: 18, name: 'Kevin Wortman'},
    { id: 14, name: 'Michael Shafae'},
    { id: 7, name: 'Mikhail Gofman'},
    { id: 4, name: 'Ning Chen'},
    { id: 10, name: 'Paul Salvador Inventado'},
    { id: 17, name: 'Shawn Wang'},
    { id: 12, name: 'Shilpa Lakhanpal'},
    { id: 2, name: 'Susan Barua'},
    { id: 8, name: 'Wenlin Han'},
    { id: 16, name: 'Yun Tian'},

    { id: 19, name: 'Sara Ghadami'},
    { id: 20, name: 'Mike Peralta'},
    { id: 21, name: 'Alexander Gauf'},
    { id: 22, name: 'Stephen May'},
    { id: 23, name: 'Mehdi Peiravi'},
    { id: 23, name: 'Teresa Shea'},
    { id: 23, name: 'Bijan Hamidi'},
    { id: 23, name: 'Mircea Dumbitrache'},
    { id: 23, name: 'Thomas Bettens'},
    { id: 23, name: ''},
    { id: 23, name: ''},
    { id: 23, name: ''},
    { id: 23, name: ''},
    { id: 23, name: ''},
    { id: 23, name: ''},
    { id: 23, name: ''},
];